### ISSUE TITLE
[Code Quality] Misleading method name

### ISSUE THREAD

**Issue by natec425** [Oscar18Guzman/reflection-api-starter#2]
https://github.com/Oscar18Guzman/reflection-api-starter/blob/c80d058db97c8c3e7cc31500cb783325134cb5bd/src/main/java/org/basecampcodingacademy/reflections/controllers/AnswerController.java#L19

`index` implies that this returns a collection, but the method returns a single object. The method should be renamed to more accurately describe what the method does.

**Comment by Oscar18Guzman** [comment]
@natec425  If I named it 'One' or 'getOne' would that be appropriate ?
